# Generated by Django 4.2 on 2024-10-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0003_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='Customer',
        ),
    ]
